
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppProvider from "@/context/AppProvider";
import { SecondAppProvider } from "@/context/SecondAppProvider";
import Navbar from "@/components/navbar";
import { useState } from "react";
import { PostProvider } from "@/context/PostContext";
import GroupChatProvider from "@/context/GroupChatProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Social App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <AppProvider>
        <SecondAppProvider>
          <PostProvider>
            <GroupChatProvider>
      <body className="bg-black text-gray-300">
        {children}
        </body>
            </GroupChatProvider>
          </PostProvider>
        </SecondAppProvider>
      </AppProvider>
    </html>
  );
}
